msgpack/msgpack-c

- include/msgpack/adaptor/tr1/unordered_map.hpp
- include/msgpack/adaptor/tr1/unordered_map_fwd.hpp
- include/msgpack/adaptor/tr1/unordered_set.hpp
- include/msgpack/adaptor/tr1/unordered_set_fwd.hpp
- test/msgpack_container.cpp
- test/object_with_zone.cpp
The typos have been pointed out by https://github.com/msgpack/msgpack-c/pull/130
Thank you @jpetso !
> Fixed typos.

- include/msgpack/unpack.hpp
See https://github.com/msgpack/msgpack-c/issues/149
and the commit d6cc5494a9dd25fe640c1602cdf1b566690c9ba7
> Fix one more memory size calculation.

- include/msgpack/unpack.hpp
- test/pack_unpack.cpp
Fixed #184
Removed redundant inline keyword form declarations.
> Added unpack function using existing zone.

- include/msgpack/sysdep.h
Added conditional include stdbool.h based on @equalsraf comment.
> Fixed #209

- include/msgpack/unpack.hpp
- include/msgpack/unpack_define.h
- include/msgpack/unpack_template.h
Added MSGPACK_ prefix to unpack macros.
> Fixed #220.

- CMakeLists.txt
- include/msgpack/adaptor/char_ptr.hpp
- include/msgpack/adaptor/check_container_size.hpp
- include/msgpack/adaptor/cpp11/array.hpp
- include/msgpack/adaptor/cpp11/array_char.hpp
- include/msgpack/adaptor/cpp11/forward_list.hpp
- include/msgpack/adaptor/cpp11/tuple.hpp
- include/msgpack/adaptor/cpp11/unordered_map.hpp
- include/msgpack/adaptor/cpp11/unordered_set.hpp
- include/msgpack/adaptor/deque.hpp
- include/msgpack/adaptor/list.hpp
- include/msgpack/adaptor/map.hpp
- include/msgpack/adaptor/set.hpp
- include/msgpack/adaptor/string.hpp
- include/msgpack/adaptor/tr1/unordered_map.hpp
- include/msgpack/adaptor/tr1/unordered_set.hpp
- include/msgpack/adaptor/vector.hpp
- include/msgpack/adaptor/vector_char.hpp
- include/msgpack/pack.hpp
- include/msgpack/unpack.hpp
- src/Makefile.am
- test/object_with_zone.cpp
Suppressed warnings on MSVC++ 64bit environment.
Added container size limit check.
> Fixed #226.

- include/msgpack/unpack.hpp
- src/unpack.c
> Fixed typo.

- erb/cpp03_define.hpp.erb
- erb/cpp03_msgpack_tuple.hpp.erb
The files that are generated by preprocess have already have the prefix.
> Added msgpack prefix to erb template files.

- include/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp
Fixed an inheriting constructor.
> Fixed #244

- include/msgpack/adaptor/vector_bool.hpp
All other containers have already been added it.
> Added a container size checking to vector<bool>.

- .travis.yml
- CMakeLists.txt
- ci/build_autotools.sh
- ci/build_cmake.sh
- include/msgpack/adaptor/boost/optional.hpp
- include/msgpack/type.hpp
- src/Makefile.am
- test/CMakeLists.txt
- test/Makefile.am
- test/boost_optional.cpp
It is enables when MSGPACK_USE_BOOST is defined.
> Added the Boost.Optional adaptor.

- .travis.yml
- CMakeLists.txt
Fixed MEMORYCHECK_COMMAND_OPTIONS location and value.
> Added valgrind version 3.10.1 from source.

- erb/cpp03_zone.hpp.erb
- include/msgpack/cpp_config.hpp
- include/msgpack/detail/cpp03_zone.hpp
- include/msgpack/detail/cpp11_zone.hpp
- include/msgpack/object.hpp
- include/msgpack/unpack.hpp
- test/object.cpp
- test/pack_unpack.cpp
The function prepares zone's chunk that has minimal size to deep copy.
> Added a clone function for msgpack::object.

- CMakeLists.txt
Makefile.am has it but CMakeLists.txt didn't have it.
> Added iterator.hpp to the installing files list.

- include/msgpack/object.hpp
- include/msgpack/object_fwd.hpp
- test/convert.cpp
Added a conversion member function to msgpack::object.
If msgpack::object is nil then returns false else returns true and sets a value.
> Fixed #357.

- example/cpp03/reuse_zone.cpp
- example/cpp11/container.cpp
- example/cpp11/non_def_con_class.cpp
Added stream outputs to suppress warnings and to help understanding.
> Fixed warnings on build with CMAKE_BUILD_TYPE=Release.

- test/object_with_zone.cpp
- test/pack_unpack.cpp
- test/pack_unpack_c.cpp
I removed warnings in test codes.
> Fix some warnings on OS X

- include/msgpack/adaptor/boost/optional.hpp
- include/msgpack/adaptor/ext.hpp
- include/msgpack/adaptor/nil.hpp
This fixes some minor typos in the comments.
> Fix minor typos

- .travis.yml
- CMakeLists.txt
- ci/build_autotools.sh
- ci/build_cmake.sh
This should help catch problems like #392 sooner.
> Add CI testing of signed/unsigned char differences

- Makefile.am
- bootstrap
Added Doxyfile to the distribution package.
Generated ChangeLog as a copy of CHANGELOG.md.
> Fixed #396.

- src/zone.c
See:
https://github.com/msgpack/msgpack-c/pull/160#commitcomment-16087596
> Fixed zone expansion algorithm.

- makedist.sh
It will replace make dist with autotools.
> Added the new packaging script.

- include/msgpack/v1/adaptor/carray.hpp
In the case the target type is char[] or const char[],
If the array is '\0' teminated, msgpack-c packs the characters before
'\0', otherwise packs all characters.
When converting, the array has the size that is greater than
msgpack::object STR's size, msgpack-c adds '\0' to just after converted
characters. Otherwise msgpack-c doesn't add '\0'.
> Improved C-Style array support.

- test/object_with_zone.cpp
Added warning supression code.
> Fixed #494

- include/msgpack/v2/unpack.hpp
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=38764
> Fixed #498.

- test/user_class.cpp
Added false positive warinig suppression code for user_class.cpp.
> Fixed #494.

- include/msgpack/fbuffer.h
Fixed fwrite return value comparison.
> Fixed #503.

- README.md
> Remove autotools instructions from README

- .travis.yml
> Fixed #525.

- test/object_with_zone.cpp
- test/user_class.cpp
Suppressed maybe unused warnings.
> Fixed #519.

- include/msgpack/gcc_atomic.hpp
- include/msgpack/sysdep.h
Building on a mipsel target did not work out of the box. These changes were needed. Hope this helps.
> Fixing building with gcc_atomic.hpp

- test/carray.cpp
- test/iterator_cpp11.cpp
- test/msgpack_c.cpp
- test/msgpack_tuple.cpp
- test/object.cpp
- test/pack_unpack.cpp
- test/reference.cpp
- test/reference_wrapper_cpp11.cpp
- test/streaming_c.cpp
- test/user_class.cpp
- test/visitor.cpp
Hi,
As I said in #537 I'm sending this PR that fix the compilation with Gtest 1.8.0 and GCC 5.4.1.
> Fix compilation with Gtest 1.8.0 and GCC 5.4.1

- appveyor.yml
- include/msgpack/v1/cpp_config.hpp
- include/msgpack/v1/object.hpp
- include/msgpack/v1/object_decl.hpp
- include/msgpack/v1/object_fwd.hpp
- include/msgpack/v1/object_fwd_decl.hpp
- include/msgpack/v1/unpack.hpp
- test/convert.cpp
- test/limit.cpp
- test/pack_unpack.cpp
- test/streaming.cpp
Added conditional [[deprecated]] attribute.
Updated zlib version.
> Fixed #534.

- include/msgpack/v2/parse.hpp
Fixed unpacker's buffer expansion logic.
> Fixed #561

- QUICKSTART-CPP.md
non reference version won't compile with 2.0 release.
> Minor fix to Quickstart (broke with 2.0)

- test/cases.cpp
Added `maybe-uninitialized` warning suppression code.
> Fixed #600.

- example/x3/parse.cpp
- include/msgpack/v2/create_object_visitor.hpp
- include/msgpack/v2/null_visitor.hpp
- include/msgpack/v2/parse.hpp
- include/msgpack/v2/x3_parse.hpp
Removed visit_float() and added visit_float32() and visit_float64()
from/to unpack visitor.
> Fixed #612

- .travis.yml
Fixed trusty's 32 bit zconf.h problem on travis-ci.
See https://bugs.launchpad.net/ubuntu/+source/zlib/+bug/1155307
> Fix trusty

- include/msgpack/v1/object.hpp
- test/object.cpp
This is a pull request implementing #633.
> Added * and -> operators to object_handle

- include/msgpack/v1/adaptor/fixint.hpp
- include/msgpack/v1/adaptor/int.hpp
Replaced comma with semi colon.
Unified cording style.
> Fixed #640.

- include/msgpack/v1/unpack.hpp
- include/msgpack/v2/parse.hpp
> Fixed #642.

- Files.cmake
- include/msgpack/v1/adaptor/detail/cpp11_convert_helper.hpp
- include/msgpack/v1/adaptor/detail/cpp11_define_array.hpp
- include/msgpack/v1/adaptor/detail/cpp11_define_map.hpp
Added `as()` checking to MSGPACK_DEFINE family.
> Fixed #644.

- README.md
- changed "small and fast" to "smaller and faster"
- made a small rewrite in the second sentence to improve readability
> Small grammatical changes made to README.md

- erb/v1/cpp03_define_map.hpp.erb
- include/msgpack/v1/adaptor/detail/cpp03_define_map.hpp
- include/msgpack/v1/adaptor/detail/cpp11_define_map.hpp
- test/user_class.cpp
Added STR type check to define_map.
> Fixed #671.

- include/msgpack/type.hpp
- include/msgpack/v1/cpp_config_decl.hpp
> Fixed #658.

- include/msgpack/timestamp.h
- include/msgpack/v1/adaptor/cpp11/chrono.hpp
> Fixed #724.

- include/msgpack/v1/vrefbuffer.hpp
- src/vrefbuffer.c
- test/msgpack_c.cpp
- test/msgpack_vref.cpp
> Adding int overflow checks to vrefbuffer

- src/unpack.c
Eliminated redundant zone allocation in unpacking process.
ARRAY and MAP is construced on the zone.
STR, BIN, and EXT refer to unpack buffer, and the buffer is reference
counted via zone (finalizer).
So zone is only needed if those types are appeared during unpacking
process.
I set zone to NULL by default. And the context has the pointer to
pointer to the zone. If the context meets ARRAY, MAP, STR, BIN, or EXT,
and zone (via pointer) is NULL, then allocate new zone.
It is lazy zone allocation strategy.
> Fixed #746.

- example/boost/asio_send_recv.cpp
Moved reserved_buffer to appropriate location.
> Fixed #752.

- include/msgpack/v1/pack.hpp
Removed SFINAE. Use size type extractor.
> Fixed #777.

- src/objectc.c
Added checking code for snprintf return value.
> Fixed #774.

- include/msgpack/v1/unpack.hpp
- include/msgpack/v2/create_object_visitor.hpp
> Replaced integer overflow with efficient way.

- include/msgpack/v2/parse.hpp
- include/msgpack/v3/parse.hpp
They seem to be unnecessary lines.
> Remove unnecessary lines from 'parse.hpp'

- QUICKSTART-CPP.md
- README.md
Fixed C++ `int main()` in the documents.
> Fixed #799.

- example/boost/msgpack_variant_mapbased.cpp
- example/cpp03/class_intrusive.cpp
- example/cpp03/class_intrusive_map.cpp
- example/cpp03/class_non_intrusive.cpp
- example/cpp03/map_based_versionup.cpp
- example/cpp03/reuse_zone.cpp
- example/cpp11/container.cpp
- test/array_ref.cpp
- test/boost_fusion.cpp
- test/boost_optional.cpp
- test/boost_string_ref.cpp
- test/boost_string_view.cpp
- test/boost_variant.cpp
- test/carray.cpp
- test/msgpack_cpp11.cpp
- test/msgpack_cpp17.cpp
- test/raw.cpp
- test/reference_wrapper_cpp11.cpp
- test/shared_ptr_cpp11.cpp
- test/size_equal_only.cpp
- test/unique_ptr_cpp11.cpp
- test/visitor.cpp
Removed `ss.str().data()` (the type of ss is std::stringstream).
Introduced variable that is const reference of `ss.str()`.
> Fixed #806.

- include/msgpack/fbuffer.h
Fixed fwrite return value comparison.
> Fixed #805.

- .github/workflows/gha.yml
`vcpkg` makes package installation and dependencies simple and straightforward.
> install depends via vcpkg on Windows

- include/msgpack/v1/adaptor/array_ref.hpp
- include/msgpack/v1/adaptor/boost/optional.hpp
- include/msgpack/v1/adaptor/cpp17/vector_byte.hpp
- include/msgpack/v1/adaptor/map.hpp
- include/msgpack/v1/adaptor/vector.hpp
- include/msgpack/v1/adaptor/vector_char.hpp
- include/msgpack/v1/adaptor/vector_unsigned_char.hpp
- include/msgpack/v1/adaptor/wstring.hpp
- test/cases.cpp
- test/convert.cpp
- test/limit.cpp
- test/object_with_zone.cpp
- test/pack_unpack.cpp
- test/streaming.cpp
- test/user_class.cpp
> Fixed many warnings/errors with macro __GNUC__(issue #850)

- .github/workflows/gha.yml
- CMakeLists.txt
Added compiler version cheking for atomic test for older compilers on cmake.
> Fixed #905.

- README.md
> Fixed misleading flag notation.

- QUICKSTART-C.md
- example/speed_test_uint32_array.c
- example/speed_test_uint64_array.c
Added msgpack_unpacked_destroy() call.
> Fixed #948.

- .github/depends/zlib.sh
- .github/workflows/gha.yml
- appveyor.yml
- include/msgpack/v1/adaptor/cpp11/chrono.hpp
Added MSGPACK_NO_BOOST guard for direct inclusion of chrono adaptor,
> Fixed #1037.
