include/msgpack/object.hpp

When printing objects with extension, falling through to type ARRAY may cause segmentation fault.

Add missing break to prevent segfault

---

erb/cpp03_zone.hpp.erb
include/msgpack/detail/cpp03_zone.hpp
include/msgpack/detail/cpp11_zone.hpp
include/msgpack/zone.h
test/zone.cpp

zone::allocate_align allocated aligned size but returned not aligned address.
This is a big problem but not reported so far. Because no one calls zone::allocate_no_align in the library code  except zone::allocate_align.
After this fix, we can call zone::allocate_align and zone::allocate_no_align.

Fixed zone alignment

---

include/msgpack/unpack.hpp
test/CMakeLists.txt
test/Makefile.am
test/limit.cpp

- Added new exceptions to explain limit over errors.
- Fixed ext maximum size problem.
Problem:
The type of m_trail was uint32_t but when parsing ext, it could be 0xffffffff + 1. +1 means type. See https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family
Solution:
Modified the type of m_trail as std::size_t. If sizeof(std::size_t) == 4, 0xffffffff size of ext is an error. If sizeof(std::size_t) == 8, 0xffffffff size of ext is not an error. m_trail is 0xffffffff + 1.
Design cohice:
I chose std::size_t as the m_trail's type instead of uint64_t intentionally. On 64 addressing bit environment, there is no problem. On 32 bit environment, there is no problem except ext with maximum size. There is only one exception in the all msgpack format. Using uint64_t to support that, it's …

- Added unpack limit.

---

include/msgpack/unpack.hpp

Prevents unused parameter error from gcc when compiled with -Wextra.

Comment unused variable name

---

include/msgpack/adaptor/float.hpp
include/msgpack/object.h
include/msgpack/object.hpp
include/msgpack/object_fwd.hpp
include/msgpack/unpack.hpp
src/objectc.c
src/unpack.c
test/msgpack_c.cpp
test/object.cpp
test/streaming_c.cpp
test/zone.cpp

The names of float format family are changed.
old                      new
dec                   -> f64
MSGPACK_OBJECT_DOUBLE -> MSGPACK_OBJECT_FLOAT
msgpack::type::DOUBLE -> msgpack::type::FLOAT
Client codes could have compile errors when it use dec, MSGPACK_OBJECT_DOUBLE or msgpack::type::DOUBLE.
The best way to fix such errors, update client code. If it can't, set MSGPACK_USE_LEGACY_NAME_AS_FLOAT macro.
Then both old names and new names are available.

Fixed #191.

---

configure.in

configure.in extracts version string for AC_INIT using sed. However, sed in OS X behaves differently from the one in Linux. `\s` and `\w` cannot be used and it appends `\n` to the output. So, I slightly modified the command to support OS X's sed.

Support OS X's sed in configure.in

---

CMakeLists.txt

Fix cmake for the case when msgpack-c uses as a subproject.

Fix cmake for subproject usage

---

erb/cpp03_define.hpp.erb
include/msgpack/adaptor/detail/cpp03_define.hpp
include/msgpack/adaptor/detail/cpp11_define.hpp
test/convert.cpp
test/msgpack_container.cpp
test/msgpack_cpp11.cpp
test/object.cpp
test/object_with_zone.cpp

enum support had been incomplete.
This fix made enum support complete.
Replaced int with auto on c++11 scoped enum.
Replaced template specializations with function overloads on operator<< and operator>> for enum.
enum can convert to object with or without zone.
When you want to adapt enum, you need to write as follows:
// NOT msgpack.hpp
enum yourenum {
elem
};
MSGPACK_ADD_ENUM(yourenum);
// msgpack.hpp should be included after MSGPACK_ADD_ENUM(...)
int main() {
msgpack::object obj(yourenum::elem);
}

Fixed #204, #202.

---

include/msgpack/sysdep.h

This builds on #221 to include FreeBSD.  At the moment, we have to patch msgpack to work for FreeBSD and OpenBSD for Neovim.

Don't include byteswap.h and FreeBSD and OpenBSD.

---

QUICKSTART-C.md
QUICKSTART-CPP.md

Fixed two small typos in descriptions of msgpack in both quickstart documents.

Small typos in quickstarts.

---

example/c/lib_buffer_unpack.c
example/c/simple.c
example/c/speed_test_uint32_array.c
example/c/speed_test_uint64_array.c
include/msgpack/unpack_template.h
src/objectc.c
src/unpack.c
src/vrefbuffer.c
src/zone.c

Avoid C99 style to interleave code and declarations in order to compile msgpackc with Visual Studion < 2013
Improve and close #246

Do not interleave code and declarations in C files

---

src/objectc.c

* Where inttypes.h is not availabale for VS<=2012 the MSVC specific macros still can be used.
* Tested with VS2010.
* See msgpack/msgpack-c#257

Make use of MSVC specific macros for format specifiers

---

include/msgpack/object.hpp
test/CMakeLists.txt
test/Makefile.am
test/json.cpp

msgpack::object stream outputs became JSON format.

Fixed #273

---

include/msgpack/adaptor/cpp11/unordered_map.hpp
include/msgpack/adaptor/cpp11/unordered_set.hpp
include/msgpack/adaptor/map.hpp
include/msgpack/adaptor/set.hpp

Using std::move for map/set is potentially more efficient (depending on the type), but also allows converting to move-only types where previously the types had to have a copy constructor.
For insert(), moving will actually prevent the copy if possible. This is the important part of the patch.
swap() is very similar to a move assignment, but needs to ensure that the `tmp` variable will afterwards contain the original contents of the target `v` variable, which we don't care about but requires a temporary variable for three-way swapping anyway, so it's a bit less optimal.
I made the moves dependent on the standard macro for C++11 since there's no need to depend on any msgpack defines in these cases, and in the cpp11/ directory there are no #ifdefs. I did not adapt any code in the tr1/ …

Use std::move (C++11) in map and set adaptors where possible.

---

include/msgpack/object.hpp
include/msgpack/object_fwd.hpp

This allows us to easily make function calls that have parameters that are dependent
upon converting from msgpack objects to concrete types. For example:
void process_args(std::tuple<int,std::string>& args)
{
...
}
process_args(obj.convert(std::make_tuple(100,"hello")))
You can get similar behavior by using obj.as<...>() but its performance is highly
dependent upon the specific compiler and whether or not r-value references are
supported.

Object conversions return the specific type that was converted.

---

include/msgpack/zbuffer.h
include/msgpack/zbuffer.hpp
test/buffer.cpp

This pull request fixes msgpack::zbuffer::write and msgpack_zbuffer_write to handle empty strings correctly.  Essentially the deflate call should be skipped entirely when there is no data to write, because it will return Z_BUFFER_ERROR and make the rest of the code think that something is wrong.
This fixes msgpack/msgpack-c#291.

Fix zbuffer empty string writes

---

CMakeLists.txt
include/msgpack/adaptor/adaptor_base.hpp
include/msgpack/adaptor/boost/fusion.hpp
include/msgpack/object.hpp
include/msgpack/type.hpp
src/Makefile.am
test/CMakeLists.txt
test/Makefile.am
test/boost_fusion.cpp

Fusion sequences can be serialized.

Added Boost.Fusion support.

---

example/cpp03/class_intrusive.cpp
example/cpp11/non_def_con_class.cpp

Refined an intrusive example. It includes base class serialization. We can switch map based and array based serialization.

Added an example of the non default constructible class.

---

include/msgpack/detail/cpp11_zone.hpp

C++11 should not use deprecated throw(std::bad_alloc) / throw(), but instead use nothrow.
Also there are two 
#if !defined(MSGPACK_USE_CPP03) 
checks in c++11 specific code. Should not this always be true?

c++11 code should use nothrow instead of throw()

---

include/msgpack/adaptor/vector.hpp

Recently was added support for non-default-constructible classes using as<T>.
But there should be the similar functionality for containers of such values.
I've just created initial version for vector, but it is not final patch I am expecting to be merged into msgpack. There must be support for other container types (e.g. map) and proper std::enable_if checks.
I do not feel comfortable to create full patch, but expect that Takatoshi Kondo or other maintainers will create polished patch. This is just suggested idea.

Support vectors of non-default-constructible values in c++11 mode

---

include/msgpack/adaptor/ext.hpp

Visual Studio 2015 warns about possible loss of value when converting from size_t to uint32_t

Fix compilation warnings about possible loss of data

---

CMakeLists.txt
include/msgpack/adaptor/cpp11/shared_ptr.hpp
include/msgpack/adaptor/cpp11/unique_ptr.hpp
include/msgpack/type.hpp
src/Makefile.am
test/CMakeLists.txt
test/Makefile.am
test/shared_ptr_cpp11.cpp
test/unique_ptr_cpp11.cpp

Added std::shared_ptr and std::unique_ptr adaptors.

---

include/msgpack/adaptor/cpp11/unordered_map.hpp
include/msgpack/adaptor/cpp11/unordered_set.hpp

```
std::unordered_map<std::string, int, std::hash<size_t> >
```
Things like above cannot be packed without this patch.

Improved templates for std::unordered_map and std::unordered_set so they handle all sorts of those

---

include/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp
include/msgpack/cpp_config.hpp

Visual Studio 2015 is c++11 compliant.
Just had to fix one error about member ref-specifiers.

Feature vs2015 support

---

include/msgpack/sbuffer.hpp

sbuffer class would benefit from move semantics, so that it can be returned from functions.
P.S.
I've moved deleted copy constructor/assignment operator (= delete) from private section to public. Scott Meyers was suggesting this, so that compiler may provide better error message (not that it is only not accessible, but that it is explicitly deleted).

Add move semantics to sbuffer in c++11 mode

---

example/c/lib_buffer_unpack.c

The example has some duplicated code that somewhat distracts from
the main processing loop. I think placing this into a separate
function improves readability of the code.

refactor example/c/lib_buffer_unpack.c

---

include/msgpack/unpack.hpp
src/unpack.c
test/pack_unpack.cpp
test/pack_unpack_c.cpp

The parameter 'offset' of unpack() function family, not unpacker family, updates only when the function successfully finished.
The parameter 'offset' used to update even if a caller passes insufficient bytes to the unpack() function family.

Fixed #348.

---

CMakeLists.txt
include/msgpack/adaptor/array_ref.hpp
include/msgpack/adaptor/cpp11/array_unsigned_char.hpp
include/msgpack/adaptor/vector_unsigned_char.hpp
include/msgpack/cpp_config.hpp
include/msgpack/type.hpp
src/Makefile.am
test/CMakeLists.txt
test/Makefile.am
test/array_ref.cpp
test/msgpack_container.cpp
test/msgpack_cpp11.cpp
test/object_with_zone.cpp

std::vector<unsigned char> and std::array<unsigned char> are mapped to BIN.
std::vector<uint8_t> and std::array<uint8_t> are mapped to BIN if uint8_t is the same type of unsigned char, otherwise mapped to ARRAY.
Added array_ref. When client wraps BIN mapped types above with array_ref as msgpack::type::array_ref<std::vector<char> >, the type is mapped to ARRAY.

Fixed #243.

---

CMakeLists.txt
Makefile.am
src/Makefile.am
test/Makefile.am

Some headers and the example directory weren't included to make dist, so I added them.

Add missing files to Makefile.am

---

include/msgpack/sysdep.h

Allow applications that include msgpack.h to predefine MSGPACK_DLLEXPORT, e.g., to not export any symbols in case of MSVC.

Only set MSGPACK_DLLEXPORT if not already defined

---

test/msgpack_basic.cpp

This code path wasn't under coverage, so this addresses that.

Add test for packing/unpacking nil

---

include/msgpack/adaptor/cpp11/reference_wrapper.hpp
test/reference_wrapper_cpp11.cpp

Previously the conversion would fail because struct object is not
generally provided for the const version of the type, but because
the wrapper would pass down the type unchanged, it would look for
exactly that missing template specialization unsuccessfully.
This is specifically an issue for std::reference_wrapper because
std::cref() returns an std::refererence_wrapper<const T>.
I haven't got GTest set up on my system, hopefully the buildbot runs the tests. If not, please run manually.
Note: convert<>() passes through the same template but it makes little sense to convert from object to const variable, because the variable is const. So I left that part unchanged.

Support to-object conversions for std::reference_wrapper<const T>.

---

QUICKSTART-C.md

The QUICKSTART-C.md has install instructions for older msgpack and the
documentation for the same. This can get confusing for users who skip the
version specified in this document—indirectly set to 0.5.5—which is easy to do
so, especially when msgpack is installed using Homebrew.
Am I correct to think that the documentation for 1.x releases is being tracked
on branches related to those versions? If yes, I'll open this PR against 1.1 or
1.2 branches.

Update install instructions and QUICKSTART-C.md

---

include/msgpack/adaptor/int.hpp

Avoided the warning when `char` does not have sign using template lazy instantiation.
Removed redundant `inline`.

Fixed #392

---

include/msgpack/sysdep.h

msgpack/predef/other/endian.h always defines both
MSGPACK_ENDIAN_LITTLE_BYTE and MSGPACK_ENDIAN_BIG_BYTE, but they're
defined to a true or false value depending on whether the system is
little/big endian.
Fix this condition to check the truthiness rather than whether it is
defined, like the other locations this macro is checked.
Closes #403
Signed-off-by: James McCoy <jamessan@jamessan.com>

Check whether MSGPACK_ENDIAN_LITTLE_BYTE is true, not defined.

---

CMakeLists.txt
QUICKSTART-C.md
QUICKSTART-CPP.md
example/c/CMakeLists.txt
msgpack.pc.in
src/Makefile.am
test/CMakeLists.txt
test/Makefile.am

libmsgpack.[a|so] is the library file for C++.
libmsgpackc.[a|so] is the library file for C.
Since version 1.0.0, the C++ parts of msgpack-c is a header only
library. So libmsgpack.* shouldn't be generated.
On the autotools building environment, removed libmsgpack.*
generation. On the cmake building environment, replaced libmsgpack.*
with libmsgpackc.* and set so-version to 2.0.0.

Fixed #395

---

include/msgpack/fbuffer.h

I have fixed a following warning of `msgpack_fbuffer_write()`.
```
warning: incompatible pointer types passing 'int (void *, const char *, unsigned int)' to parameter of type 'msgpack_packer_write' (aka 'int (*)(void *, const char *, size_t)') [-Wincompatible-pointer-types]
msgpack_packer* pk = msgpack_packer_new(fp, msgpack_fbuffer_write);
^~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/msgpack/1.3.0/include/msgpack/pack.h:129:76: note: passing argument to parameter 'callback' here
inline msgpack_packer* msgpack_packer_new(void* data, msgpack_packer_write callback)
```

Fixed an incompatible type warning

---

include/msgpack/adaptor/boost/msgpack_variant.hpp
include/msgpack/adaptor/nil.hpp
test/boost_variant.cpp

Added nil typedef for existing codes.

Replaced nil with nil_t.

---

include/msgpack/adaptor/nil.hpp

Changed macro name from MSGPACK_USE_LEGACY_NIL to
MSGPACK_DISABLE_LEGACY_NIL. msgpack-c shouldn't make compile error on
existing codes by default without major version up.
So if you want to disable msgpack::type::nil, you need to define
MSGPACK_DISABLE_LEGACY_NIL macro.

Fixed existing code compile error problem.

---

include/msgpack/sysdep.h

This is important because the integer definitions clash with the integer definitions in the rapidjson C++ library, but only at the level of signed/unsigned integers.  We use both libraries in the CoolProp library

Add signed flags to MSVC integer definitions

---

include/msgpack/v1/adaptor/check_container_size_decl.hpp

``#include <stdint.h>`` is invalid in MSVC 9 2008 .  Using the system dependent header does work in my testing with MSVC9, and should be safe for other compilers I think.

Replace stdint.h header in check_container_size_decl.hpp

---

include/msgpack/v1/adaptor/detail/cpp11_msgpack_tuple.hpp
include/msgpack/v1/adaptor/detail/cpp11_msgpack_tuple_decl.hpp

Replaced the inheriting constructor with a forwarding constructor.
Removed the template constructors that are covered by the forwarding constructor.
Added std::forward() to make_tuple.
Added conversion constructor.
Moved msgpack::type::tuple to
include/msgpack/v1/adaptor/detail/cpp11_msgpack_tuple_decl.hpp from
include/msgpack/v1/adaptor/detail/cpp11_msgpack_tuple.hpp.
msgpack::type::tuple_cat requires the class template tuple definition.

Fixed #422.

---

include/msgpack/v1/adaptor/detail/cpp11_msgpack_tuple_decl.hpp

When I fixed #422 by #426, I removed existing constructors too much. I reverted the constructors.

Undo-ed overly removed constructors.

---

include/msgpack/sysdep.h

This PR is additional patch for #270.
'TARGET_OS_IPHONE' is defined in TargetConditionals.h.
For that reason, the iOS detector doesn't work.

Fixed the broken float en/decoder on iOS

---

erb/v1/cpp03_zone.hpp.erb
include/msgpack/v1/detail/cpp03_zone.hpp

Fixed a pointer operation problem at msgpack::zone::chunk_list::clear().
It was only happened on C++03.

Fixed #440.

---

include/msgpack/v1/adaptor/adaptor_base.hpp
include/msgpack/v2/adaptor/adaptor_base.hpp
include/msgpack/v2/adaptor/adaptor_base_decl.hpp

Updated msgpack::v1::operator<< and >> implementation.
Those functions refer to current version of convert, pack, object, and object_with_zone.

Fixed #442.

---

include/msgpack/v1/object.hpp

Replaced passed by value with passed by rvalue reference on
msgpack::object_handle's constructor.

Fixed #446.

---

include/msgpack/v2/adaptor/nil_decl.hpp

Note: In v1, type::nil is defined if NOT defined MSGPACK_DISABLE_LEGACY_NIL.

type::nil is defined only if MSGPACK_USE_LEGACY_NIL in v2.

---

CMakeLists.txt
QUICKSTART-CPP.md
README.md
example/cpp03/CMakeLists.txt
include/msgpack/object.hpp
include/msgpack/v1/adaptor/adaptor_base_decl.hpp
include/msgpack/v1/object.hpp
include/msgpack/v1/object_fwd.hpp
include/msgpack/v1/unpack.hpp
include/msgpack/v2/object.hpp
include/msgpack/v2/object_decl.hpp
include/msgpack/v2/object_fwd.hpp
include/msgpack/v2/object_fwd_decl.hpp
src/Makefile.am
test/Makefile.am
test/convert.cpp
test/user_class.cpp

Removed MSGPACK_DISABLE_LEGACY_CONVERT from v2. Those APIs are removed
from v2.

Removed obsolete APIs form v2.

---

include/msgpack/v1/object.hpp

JSON doesn't have `nil` but has `null`.
msgpack::object JSON output uses `null` when the object is nil_t.

Fixed #457.

---

erb/cpp03_zone.hpp.erb
include/msgpack/detail/cpp03_zone.hpp

Fixed a pointer operation problem at msgpack::zone::chunk_list::clear().
It was only happened on C++03.

Backported #441 to cpp-1.4.

---

example/cpp03/stream.cpp
include/msgpack/v2/unpack.hpp
include/msgpack/v2/unpack_decl.hpp
test/CMakeLists.txt
test/Makefile.am
test/cases.cpp
test/streaming.cpp
test/unpack_visitor.cpp
test/visitor.cpp

The current unpacking APIs are constructed on the visitor mechanism.
(Fixed #418)

Added a visitor version of unpack API,

---

appveyor.yml
erb/v1/cpp03_define_map.hpp.erb
example/c/lib_buffer_unpack.c
include/msgpack/v1/adaptor/adaptor_base_decl.hpp
include/msgpack/v1/adaptor/boost/msgpack_variant.hpp
include/msgpack/v1/adaptor/detail/cpp03_define_map.hpp
include/msgpack/v1/adaptor/int.hpp
test/CMakeLists.txt
test/Makefile.am
test/inc_adaptor_define.cpp
test/msgpack_basic.cpp
test/msgpack_c.cpp

Fixed #463.

---

example/c/user_buffer_unpack.c
include/msgpack/object.h
include/msgpack/sysdep.h
src/objectc.c

In order to print the msgpack object in a memory buffer.
Similar to msgpack_object_print(), but prints in a given, allocated buffer.
Basically tested it with ./user_buffer_unpack.

Add msgpack_object_print_buffer() function

---

src/objectc.c

msgpack_object_print used fwrite to write binary data to a stream. The intention
of the function is to produce a human-readable representation of the object for
debugging purposes. Having arbitrary data dumped as is can cause issues with
terminals that interpret it as control sequences.
This change prints printable characters as is and unprintable characters as
hex-escapes ("\xNN"). Note that UTF-8 encoded characters will now be printed as
escaped sequence of UTF-8 bytes. This is an acceptable compromise, as doing
otherwise would require a light form of UTF-8 decoding and BIN-typed objects
should not be used to transport UTF-8 strings anyway (STR should be used
instead).

Improve bin printer for unprintable characters.

---

src/objectc.c

I did this PR, analogous to PR #497. Besides compilation, didn't actually tested it. Tell me if you spot any issues.

Print unprintable characters in memory buffer

---

example/cpp11/non_def_con_class.cpp
include/msgpack/v1/adaptor/map.hpp

In a C++11 project, I based my msgpack code on the example from `cpp11/non_def_non_class`.  I believe it is very elegant, as the only thing I have to do to adapt custom classes is implementing an as<>() method. That is really lovely!
Unfortunately, my code broke (tries to use the deleted default constructor) when I tried do the following
obj.as<std::map<int, my> >()
The reason is that msgpack-C++ is not using the `as<std::map>()` implementation, but falls back to the `convert<std::map>()` implementation, because `has_as<int>` is `false`.  The proposed pull request fixes the problem, and adapts the `non_def_non_class` example to demonstrate the problem and its fix.

enable as<std::map>() use if key OR value has as() implementation

---

include/msgpack/unpack.h
src/unpack.c
test/streaming_c.cpp

This new function is an extension of the original msgpack_unpacker_next()
where it now adds third argument to store the number of parsed bytes for
the returned buffer upon a MSGPACK_UNPACK_SUCCESS case.
This is useful for cases where the caller needs to optimize memory usage
in the original buffer,s so upon success retrieval of the object, it can
later deprecate the already 'parsed' bytes.
For more details about the origins of this function please refer to the
following issue on github:
https://github.com/msgpack/msgpack-c/issues/514
Signed-off-by: Eduardo Silva <eduardo@treasure-data.com>

unpack: new msgpack_unpacker_next_with_size() function

---

include/msgpack/gcc_atomic.hpp

Removed MSGPACK_ENABLE_GCC_CXX_ATOMIC macro in gcc_atomic.hpp since it is not defined in user code but the header is included. So this code would not be active then.

Removed MSGPACK_ENABLE_GCC_CXX_ATOMIC macro

---

include/msgpack/v1/object.hpp

Changing the stream to `std::hex` mode should only affect the current character; otherwise printing some msgpack with a list like this: `[123, "string\\u0003", 123]` (123 decimal) ends up printing `[123, "string\\u0003", 7b]`, as `std::hex` is sticky.

Save the flags of the stream

---

src/objectc.c

This change make safe for `char = signed char`.
As the spec, argment of `isprintf()` must be representabe as an
`unsigned char` (or equal to EOF, not expected here).
Additionally, some implementation define it as a macro using array,
then it cause warning "array subscript has type `char` [-Wchar-subscripts]"
with `char` argments.

Make sure to pass `unsigned char` to `isprint()`

---

include/msgpack/v2/parse.hpp

Empty arrays/maps can cause spurious calls to visitor functions.  The attached test case parses the message `[{},{}]` and produces the following output:
start_array 2
start_array_item
start_map 0
end_map
end_array_item
start_array_item
start_map_key
start_map 0
end_map
end_array_item
end_array
Notice the start_map_key call occurs outside of the map (and in fact there should be no keys for an empty map).
[msgpack_bug.txt](https://github.com/msgpack/msgpack-c/files/815303/msgpack_bug.txt)

Fixed spurious start_map_key/start_array_item calls

---

CMakeLists.txt

It's nice to be able to build against the distro-provided dynamically-linked version of a library instead of having to build the static version to run examples/tests.

Enable building against dynamically-linked Boost

---

include/msgpack/v1/adaptor/array_ref.hpp
include/msgpack/v1/adaptor/map.hpp
include/msgpack/v1/adaptor/vector.hpp
include/msgpack/v1/adaptor/vector_char.hpp
include/msgpack/v1/adaptor/vector_unsigned_char.hpp
test/object_with_zone.cpp
test/user_class.cpp

Replaced __GNUC_MINOR__ 6 with 7 for suppress maybe-uninitialized.

Fixed #536.

---

include/msgpack/sysdep.h
include/msgpack/vrefbuffer.h

Check for UNIX and APPLE instead of not WIN32 before POSIX specific headers and functions to support embedded operating systems.

Detect POSIX compatiblity explicit

---

src/objectc.c

This patch fix the following cross compile error:
src/objectc.c:342:9: error: field precision specifier '.*' expects argument of type 'int', but argument 4 has type 'uint32_t' [-Werror=format=]

Pass wildcard precision of snprintf as int

---

include/msgpack/v2/parse.hpp

Reset m_cs to MSGPACK_CS_HEADER after visitor called.
NOTE:
The problem happens only when parser is used directly. Unpacker doesn't have the same problem.
Because unpacker calls `reset()` function. See https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v2/unpack.hpp#L95

Fixed #584.

---

include/msgpack/sysdep.h

There is a compiler error if Boost.Asio and Msgpack-c are both used in the same project on Win32 plarform. The root cause is 'WinSock.h' header file is included indirectly by Msgpack library when '<windows.h>' is included. The fix prevents including such unnecessary header files.

Fix 'WinSock.h has already been included' compiler error.

---

CMakeLists.txt
example/boost/CMakeLists.txt
example/cpp03/CMakeLists.txt
example/cpp11/CMakeLists.txt
example/x3/CMakeLists.txt
msgpack-config.cmake.in
test/CMakeLists.txt

Add support for CMake find_package command to msgpack. The package
exports the two targets msgpackc-static and msgpackc if shared is
enabled. The CMake find_package command works after installation
of msgpack and during build of another project which adds msgpack
as sub project via add_subdirectory command.

Add cmake package config support

---

include/msgpack/unpack_template.h

GCC 7 added a new diagnostic, -Wimplicit-fallthrough, which is enabled
with -Wextra that warns about implicitly falling through a case
statement.
[  4%] Building C object CMakeFiles/msgpackc-static.dir/src/unpack.c.o
/usr/lib/gcc-snapshot/bin/gcc   -I/home/mccoyj1/src/msgpack-c/. -I/home/mccoyj1/src/msgpack-c/include -I/home/mccoyj1/src/msgpack-c/build/include  -g -O2 -fdebug-prefix-map=/home/mccoyj1/src/msgpack-c=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -Wall -Wextra -Werror -g -O3 -o CMakeFiles/msgpackc-static.dir/src/unpack.c.o   -c /home/mccoyj1/src/msgpack-c/src/unpack.c
In file included from /home/mccoyj1/src/msgpack-c/src/unpack.c:283:0: …

Comment the intentional fallthrough to default from _fixed_trail_again

---

include/msgpack/v1/adaptor/detail/cpp03_define_array.hpp

Fixes build with gcc7
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Comment intentional fallthrough in case statements

---

.travis.yml
CMakeLists.txt
appveyor.yml
example/cpp03/CMakeLists.txt
example/x3/CMakeLists.txt

At the moment the CI doesn't test all Boost test and examples. Make all Boost components mandatory if MSGPACK_BOOST is ON. Additionally disable boost on AppVeyor when the compiler don't match the default compiler because the pre-installed software is only compiled with the default compiler.

cmake: Enable all Boost tests on CI

---

test/user_class.cpp

When I execute cmake `-DMSGPACK_CXX11=OFF`, gcc 7.1 reports the warning.
I've already added the warning suppression pragma, but it doesn't work
in this case. So I added explicit initializing code even if it is redundant.

Suppressed gcc 7.1 `maybe-uninitialized` warning.

---

include/msgpack/vrefbuffer.h

Using msgpack-c under QNX leads to an error because of the iovec strcut being redefined.
I added the defines for the QNX compilers to include the appropriate header.

Add defines for QNX build

---

QUICKSTART-C.md

As per: https://github.com/Homebrew/brew/blob/master/docs/FAQ.md
> Homebrew is designed to work without using sudo. You can decide to use it but we strongly recommend not to do so. If you have used sudo and run into a bug then this is likely to be the cause. Please don’t file a bug report unless you can reproduce it after reinstalling Homebrew from scratch without using sudo.

Don't sudo with brew in QUICKSTART-C.md

---

.travis.yml

It's temporary fix.
Need to find a way to install the 32 bit version of zlib on `trusty` dist in the future.

Set `precise` explicitly to fix 32bit zlib missing problem.

---

include/msgpack/v1/unpack.hpp
include/msgpack/v2/parse.hpp
include/msgpack/v2/unpack.hpp
src/unpack.c
test/pack_unpack.cpp
test/pack_unpack_c.cpp
test/visitor.cpp

<<< Breaking change >>>
In the functions unpack() and parse(),
Old behavior: If any parse error is happend, offset is NOT updated.
New behavior: If any parse error is happend, offset is updated to the
position the error happened.
It helps MessagePack format error analysis.
If you want to old behavior, copy the original value of offset and then call unpack()
and/or parse().

Fixed #637.

---

include/msgpack/vrefbuffer.h

This was needed for neovim
Hopefully, in the next release https://github.com/neovim/neovim/ will build in NetBSD without any errors. It downloads this as a dependency if not present in the system.

Include <sys/uio.h> in NetBSD too.

---

include/msgpack/v1/object.hpp

Casting to void* make gcc happy since its upset about
object types and rightly so
Fixes
'void* memcpy(void*, const void*, size_t)' copying an object of non-trivial type 'struct msgpack::v2::object' from an array of 'const msgpack_object' {aka 'const struct msgpack_object'} [-Werror=class-memaccess]
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Fix -Werror=class-memaccess with gcc8

---

fuzz/unpack_pack_fuzzer.cpp

This is a short lived bug in the fuzzer implementation in which the limits were not set correctly. It adds limits for depth and ext as detailed in https://github.com/msgpack/msgpack-c/blob/c6c31dc5cd56ad0f8bafd0db82e013aa92cea5c3/include/msgpack/v1/unpack_decl.hpp#L94-L95.
Credit to OSS-Fuzz

Fix the fuzzer by setting limits for depth and ext.

---

fuzz/unpack_pack_fuzzer.cpp

This is an attempt to keep the fuzzer from OOMing while running. The limit of 10,000 looks to allow memory usage to be right around the limits that OSS-fuzz provides. Lowering this by a factor of 10 should keep us healthily under the limit while still providing useful data.
Thanks!

Lower limits for the fuzzer inputs

---

include/msgpack/pack.h

Without this patch, link error occurs below in "msvc".
```
error LNK2019: unresolved external symbol msgpack_pack_object referenced in function 
```
I think that it is correction omission of below commit.
https://github.com/msgpack/msgpack-c/commit/a4af97b32c018cbf0ce91153c937902c13e0d412

Add dll export for msvc

---

CMakeLists.txt

Since FULL_PATH_NAMES = YES, Doxygen includes the full build path to the
file in the documentation.  This is most prevalent in the <title>
attribute for a file.
Setting STRIP_FROM_PATH = ${CMAKE_CURRENT_SOURCE_DIR}/include means that
only the relevant portion of the path (that which the user would need to
use) is included.
```diff
--- a/msgpack_8h.html	2018-05-12 14:03:34.098715879 -0400
+++ b/msgpack_8h.html	2018-05-12 14:04:17.386349607 -0400
@@ -5,7 +5,7 @@
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.13"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
-<title>MessagePack for C: /home/jamessan/src/debian.org/pkg-vim/msgpack-c/include/msgpack.h File Reference</title>
+<title>MessagePack for C: msgpack.h File …
```

Strip the build path from generated documentation

---

include/msgpack/v1/cpp_config.hpp

Fix MSGPACK_DEPRECATED for MSVC 1914 with /Zc:__cplusplus
@see https://docs.microsoft.com/cpp/build/reference/zc-cplusplus

Fix MSGPACK_DEPRECATED for MSVC 1914 with /Zc:__cplusplus

---

include/msgpack/v1/object.hpp
test/msgpack_basic.cpp

Fixed `msgpack::object` packing visitor and equal comparison visitor.
NOTE:
In the function `visit_ext(const char* v, uint32_t size)`, v contains
type and size means buffer `v` size. See #175.

Fixed #754.

---

include/msgpack/v1/adaptor/array_ref.hpp

I found this self-including header using IWYU ( https://github.com/include-what-you-use/include-what-you-use ), as it tripped an assertion.

Fix header circular reference

---

include/msgpack/v1/zbuffer.hpp
include/msgpack/zbuffer.h

Buffer is expanded not only Z_OK, but also Z_BUF_ERROR case.

Fixed #794.

---

include/msgpack/vrefbuffer.h

https://github.com/msgpack/msgpack-c/blob/f65c26e280f3f2e05c45d2d7b9e21a0b494b0fcd/include/msgpack/vrefbuffer.h#L16 needs `__HAIKU__`.
Reference:
https://github.com/haikuports/haikuports/issues/3980

Add "defined(__HAIKU__)", closes #796

---

include/msgpack/vrefbuffer.h

This is needed when cross-compiling msgpack-c for OpenWrt.
Without it, compilation fails:
```
In file included from /build/staging_dir/target-powerpc_8540_musl/usr/include/msgpack.h:22:0,
from main.c:35:
/build/staging_dir/target-powerpc_8540_musl/usr/include/msgpack/vrefbuffer.h:19:8: error: redefinition of 'struct iovec'
struct iovec {
^~~~~
```

Include <sys/uio.h> in Linux

---

include/msgpack/sysdep.h
src/objectc.c
test/msgpack_c.cpp

In MSGPACK_CHECKED_CALL, the return value of snprintf is incorrectly
assumed to mean success if it is less than or equal to the buffer size.
The call should only be considered a success if the return value is less
than the buffer size.
This commit adds two unit tests that illustrates the issue and fixes the
issue, making the unit tests pass.

Correctly check return value of snprintf

---

test/msgpack_cpp11.cpp

I recently updated the Debian package for msgpack-c to 3.2.1 and found that there were a [number of build failures](https://buildd.debian.org/status/logs.php?pkg=msgpack-c&ver=3.2.1-1&suite=experimental).  It appears that all of the 32-bit architectures (except m68k) failed with this error:
```
[20/122] /usr/bin/c++   -I../build-gtest/install/include -I../include -Iinclude -DMSGPACK_DEFAULT_API_VERSION=3 -std=c++11 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2    -Wall -Wextra -Wconversion -MD -MT test/CMakeFiles/msgpack_cpp11.dir/msgpack_cpp11.cpp.o -MF test/CMakeFiles/msgpack_cpp11.dir/msgpack_cpp11.cpp.o.d -o test/CMakeFiles/msgpack_cpp11.dir/msgpack_cpp11.cpp.o -c ../test/msgpack_cpp11.cpp
FAILED: …
```

Fix msgpack_cpp11 tests on 32-bit architectures

---

.github/depends/boost.sh
.github/workflows/gha.yml

Caching `boost` can save running time of CI.
On Mac, we reduced the time from 40s (install package) to 7s (restore cache),
and on Linux, from 1m 50s (install package) to 7s (restore cache).
Also, caching depends on Windows can save about 50 seconds.

use cache in github actions

---

QUICKSTART-C.md

Improve this document:
- add "build with cmake" section
- remove "build with visual studio 2008" section
*Visual Studio 2008* is too old. It's hard to imagine anyone else using it. And it can be replaced by *cmake*. I even recommend removing this code from future versions of msgpack-c.
Besides, the link of `dev-libs/msgpack` is invalid. I hope someone who is proficient in `Gentoo Linux` can fix it.

update the install section

---

.github/workflows/gha.yml
include/msgpack/zbuffer.h

- fix github actions failure
`apt-get update` downloads the package lists from the repositories and updates them to get information on the newest versions of packages and their dependencies.
Fix the CI errors that mentioned in this issue: https://github.com/msgpack/msgpack-c/issues/857
- use C style casts instead of C++ style casts in zbuffer.h
`static_cast` and `reinterpret_cast` are invalid in pure C projects.
Fix: https://github.com/msgpack/msgpack-c/issues/858

fix github actions failure and use C style casts instead of C++ style casts in zbuffer.h

---

src/vrefbuffer.c
test/CMakeLists.txt
test/buffer.cpp
test/buffer_c.cpp
test/msgpack_c.cpp

- vrefbuffer: set default ref_size and chunk_size, and add test cases.
- divide `buffer.cpp` into `buffer.cpp` and `buffer_c.cpp` because `iovec` is redefined (in `include/msgpack/v1/vrefbuffer.hpp` and `include/msgpack/vrefbuffer.h` )

vrefbuffer: set default ref_size and chunk_size

---

example/c/simple_c.c

unsigned int and size_t are not the same type on x64 platforms. The compiler gave a warning that was treated as an error.

Fixed warning in Visual Studio

---

example/c/CMakeLists.txt
example/c/jsonconv.c
include/msgpack/pack.h

- Pack json string to msgpack format data.
`int msgpack_pack_jsonstr(msgpack_packer *pk, const char *jsonstr)`
- Convert msgpack format data to json string.
`int msgpack_object_print_jsonstr(char *buffer, size_t length, const msgpack_object o)`

convert between msgpack and json via cJSON library

---

.github/workflows/gha.yml

There was an error in this [test](https://github.com/msgpack/msgpack-c/runs/703562934?check_suite_focus=true), but it was not marked as a failure.
```
Could NOT find Boost (missing: Boost_INCLUDE_DIR chrono context system timer)
```
So we need to add `BOOST_ROOT` and check error.

fix cannot find boost error

---

include/msgpack/sbuffer.h

Avoid passing null pointer to `memcpy()`.
Fixed the following error mentioned by @jamessan in issue #881:
```
runtime error: null pointer passed as argument 2, which is declared to never be null
```

check null pointer before using memcpy()

---

include/msgpack/v1/adaptor/cpp11/chrono.hpp

Replaced static_cast with boost::numeric_cast to detect invalid cast
easier.

Fixed undefined behavior in chrono converting.

---

include/msgpack/unpack_define.hpp
include/msgpack/v1/adaptor/ext.hpp
include/msgpack/v1/adaptor/ext_decl.hpp
include/msgpack/v1/fbuffer.hpp
include/msgpack/v1/sbuffer.hpp
include/msgpack/v1/unpack.hpp
include/msgpack/v1/vrefbuffer.hpp
include/msgpack/v1/zbuffer.hpp
include/msgpack/v2/create_object_visitor.hpp
include/msgpack/v2/parse.hpp
include/msgpack/v3/parse.hpp

Applied *buffer buf and len checking assert.
Avoided needless code execution if buf is nullptr.

Replaced assert with BOOST_ASSERT.

---

example/cpp11/container.cpp

It also provides a consistent coding style with the rest of C++11
examples.

Let the compiler deduce the type

---

src/objectc.c
test/msgpack_c.cpp

Don't abort serialization when running into empty strings in msgpack_object_print_buffer().
Added a couple of unit tests to test empty string cases.

Fix #941: empty strings break msgpack_object_print_buffer() (C)

---

CMakeLists.txt
README.md

This is an attempt at increasing the visibility of tests for the C branch (c_master).
- Small addition to README to mention gtest and show how to run tests
- Turn on output-on-failure by default for tests
Note: see how I turned on output-on-failure in the root `CMakeLists.txt`. I don't know much about CMake and I'm not quite sure it is the right way (but it is very helpful :) ).

C: Increase tests visibility (Issue #943)

---

.github/workflows/gha.yml

If sanitizer detects an error, it will lead to a non-zero exit code.

Set `-fno-sanitize-recover=all` compiler option

---

include/msgpack/v1/adaptor/v4raw.hpp

Behaviour of memcmp is undefined if any of pointers passed to it is null.
See https://en.cppreference.com/w/c/string/byte/memcmp for details.
UB was detected on test MSGPACK_V4RAW_REF.pack_unpack_fix_l with UB-sanitizer.

Fix UB in v4raw_ref::operator==

---

include/msgpack/v1/unpack.hpp

Called memcpy only if STR/BIN size > 0.

Fixed #956.

---

cmake/sysdep.h.in
include/msgpack/zone.h

These two commits improve the portability of the C implementation such that they can be successfully built for CHERI, and thus Arm's experimental Morello prototype. Please see the individual commits for the detailed rationale behind the changes.

Support building for CHERI/Morello

---

erb/v1/cpp03_zone.hpp.erb
include/msgpack/sysdep.hpp
include/msgpack/v1/detail/cpp03_zone.hpp
include/msgpack/v1/detail/cpp11_zone.hpp
test/zone.cpp

Improved alignment calculation logic.

Ported #962 to C++.

---

CMakeLists.txt

This option explicitly controls the generation of targets related to
Doxygen generation, rather than relying solely on whether Doxygen is
discovered.
It is enabled by default to preserve existing behavior, but if disabled
then no Doxygen targets will be generated. This is useful when the
library is included via CMake's `add_subdirectory()`.

Add option `MSGPACK_BUILD_DOCS`.

---

CMakeLists.txt

Prior to the c_master/cpp_master split, this is where the files were installed (c.f., https://github.com/msgpack/msgpack-c/blob/6e7deb809120881634b3ca895e66b2a946084f34/CMakeLists.txt#L454) but this was changed to use "lib/" directly when updating the C++-only packaging.
Re-instate the use of CMAKE_INSTALL_LIBDIR so the user can control where they are installed and they follow the typical convention for location.

Install version/config files under CMAKE_INSTALL_LIBDIR

---

.github/depends/zlib.sh
.github/workflows/gha.yml
appveyor.yml
include/msgpack/predef/os/linux.h
include/msgpack/sysdep.hpp

According to [one](https://sourceforge.net/p/predef/wiki/OperatingSystems/) and [two](http://www.faqs.org/docs/Linux-HOWTO/GCC-HOWTO.html#INDEX.25) `linux` macro is obsolete, `__linux__` should be used instead. Quoting [two](http://www.faqs.org/docs/Linux-HOWTO/GCC-HOWTO.html#INDEX.25):
> If you are writing code that uses Linux-specific features, it is a good idea to enclose the nonportable bits in
#ifdef \_\_linux__
/* ... funky stuff ... */
#endif /* linux */
Use \_\_linux__ for this purpose, not linux. Although the latter is defined, it is not POSIX compliant.
It turns out that `linux` macro undefined when compiling project with `-std=c++xy` family of compilation flags, e.g. with `-std=c++11`

fix detection of linux based os

---

include/msgpack/v1/pack.hpp
test/msgpack_basic.cpp

pack double and float more size efficient

---

erb/v1/cpp03_zone.hpp.erb
include/msgpack/v1/detail/cpp03_zone.hpp
include/msgpack/v1/detail/cpp11_zone.hpp

Removed invalid `noexcept` from zone's constructor.

Fixed #1029.

---

.github/workflows/gha.yml
include/msgpack/preprocessor/config/config.hpp

The [new MSVC preprocessor](https://devblogs.microsoft.com/cppblog/announcing-full-support-for-a-c-c-conformant-preprocessor-in-msvc) is now standard-conformant. It should use the standard (strict) macro definition if `/Zc:preprocessor` is specified.

Fix config for new MSVC preprocessor

---

CMakeLists.txt
appveyor.yml
example/cmake/CMakeLists.txt
msgpackc-config.cmake.in

Change the CMake package name to msgpackc, as requested in https://github.com/msgpack/msgpack-c/issues/1043#issuecomment-1372169699 . After this change, to find the C library in the system, it is necessary to call:
~~~cmake
find_package(msgpackc REQUIRED)
~~~
instead of the previously used:
~~~cmake
find_package(msgpack REQUIRED)
~~~
Fix https://github.com/msgpack/msgpack-c/issues/1043 .

Change CMake package name of C library to msgpackc
